import type { SystemStateRecord } from "./shureFundModels";

export const initialSystemState: SystemStateRecord = {
  currentUserId: "user-commercial",
  users: [
    { id: "user-commercial", name: "Maya Singh", role: "commercial" },
    { id: "user-professional", name: "Owen Blake", role: "professional" },
    { id: "user-treasury", name: "Leah Mercer", role: "treasury" },
    { id: "user-funder", name: "Harbour Capital", role: "funder" },
    { id: "user-contractor", name: "Hawthorne Build", role: "contractor" },
    { id: "user-subcontractor", name: "Pinnacle Facades", role: "subcontractor" },
  ],
  projects: [{ id: "project-aurora", name: "Aurora Civic Centre", status: "active", reserveBuffer: 50000 }],
  stages: [
    {
      id: "stage-foundation",
      projectId: "project-aurora",
      name: "Foundation Package",
      status: "blocked",
      requiredAmount: 160000,
      releasedAmount: 0,
      evidenceRequirementIds: ["foundation-photos", "foundation-checklist"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      approvalSequence: ["commercial", "professional", "treasury"],
      contractorName: "Hawthorne Build",
      subcontractorName: "Groundline Civils",
      overrideActive: false,
      disputes: [],
      variations: [],
    },
    {
      id: "stage-frame",
      projectId: "project-aurora",
      name: "Structural Frame",
      status: "blocked",
      requiredAmount: 240000,
      releasedAmount: 0,
      evidenceRequirementIds: ["frame-pack", "frame-checklist"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      contractorName: "Hawthorne Build",
      subcontractorName: "North Steel Systems",
      overrideActive: false,
      disputes: [
        {
          id: "dispute-frame-1",
          stageId: "stage-frame",
          title: "Certified value under review",
          reason: "Delivery note quantity does not match certified tonnage.",
          disputedAmount: 20000,
          status: "open",
          openedBy: "user-contractor",
          openedAt: "2026-04-04T09:30:00.000Z",
        },
      ],
      variations: [],
    },
    {
      id: "stage-envelope",
      projectId: "project-aurora",
      name: "Envelope Works",
      status: "blocked",
      requiredAmount: 120000,
      releasedAmount: 0,
      evidenceRequirementIds: ["envelope-approval", "weatherproofing-checklist"],
      requiredApprovalRoles: ["commercial", "professional"],
      contractorName: "Hawthorne Build",
      subcontractorName: "Pinnacle Facades",
      overrideActive: false,
      onHold: true,
      disputes: [],
      variations: [
        {
          id: "variation-envelope-1",
          stageId: "stage-envelope",
          title: "Weatherproofing detail variation",
          reason: "Additional sealing detail required for revised facade interface.",
          amountDelta: 15000,
          status: "pending",
          createdBy: "user-contractor",
          createdAt: "2026-04-04T12:00:00.000Z",
        },
      ],
    },
  ],
  evidenceRequirements: [
    {
      id: "foundation-photos",
      stageId: "stage-foundation",
      label: "Foundation inspection photos",
      type: "file",
      required: true,
    },
    {
      id: "foundation-checklist",
      stageId: "stage-foundation",
      label: "Concrete pour checklist",
      type: "form",
      required: true,
    },
    {
      id: "frame-pack",
      stageId: "stage-frame",
      label: "Steel delivery pack",
      type: "file",
      required: true,
    },
    {
      id: "frame-checklist",
      stageId: "stage-frame",
      label: "Frame erection checklist",
      type: "form",
      required: true,
    },
    {
      id: "envelope-approval",
      stageId: "stage-envelope",
      label: "Facade mock-up approval",
      type: "file",
      required: true,
    },
    {
      id: "weatherproofing-checklist",
      stageId: "stage-envelope",
      label: "Weatherproofing checklist",
      type: "form",
      required: true,
    },
  ],
  evidence: [
    {
      id: "evidence-foundation-photos",
      stageId: "stage-foundation",
      type: "file",
      status: "accepted",
      requirementId: "foundation-photos",
      name: "Foundation inspection photos",
      submittedAt: "2026-04-02T08:20:00.000Z",
    },
    {
      id: "evidence-foundation-checklist",
      stageId: "stage-foundation",
      type: "form",
      status: "accepted",
      requirementId: "foundation-checklist",
      name: "Concrete pour checklist",
      submittedAt: "2026-04-02T09:00:00.000Z",
    },
    {
      id: "evidence-frame-pack",
      stageId: "stage-frame",
      type: "file",
      status: "requires_more",
      requirementId: "frame-pack",
      name: "Steel delivery pack",
      submittedAt: "2026-04-03T10:15:00.000Z",
    },
    {
      id: "evidence-frame-checklist",
      stageId: "stage-frame",
      type: "form",
      status: "pending",
      requirementId: "frame-checklist",
      name: "Frame erection checklist",
      submittedAt: "2026-04-03T10:45:00.000Z",
    },
    {
      id: "evidence-envelope-approval",
      stageId: "stage-envelope",
      type: "file",
      status: "pending",
      requirementId: "envelope-approval",
      name: "Facade mock-up approval",
      submittedAt: "2026-04-03T13:00:00.000Z",
    },
  ],
  approvals: [
    { id: "approval-foundation-commercial", stageId: "stage-foundation", role: "commercial", status: "pending" },
    { id: "approval-foundation-professional", stageId: "stage-foundation", role: "professional", status: "pending" },
    { id: "approval-foundation-treasury", stageId: "stage-foundation", role: "treasury", status: "pending" },
    { id: "approval-frame-commercial", stageId: "stage-frame", role: "commercial", status: "pending" },
    { id: "approval-frame-professional", stageId: "stage-frame", role: "professional", status: "pending" },
    { id: "approval-frame-treasury", stageId: "stage-frame", role: "treasury", status: "pending" },
    { id: "approval-envelope-commercial", stageId: "stage-envelope", role: "commercial", status: "pending" },
    { id: "approval-envelope-professional", stageId: "stage-envelope", role: "professional", status: "pending" },
  ],
  ledgerAccounts: [
    { id: "account-project-aurora", name: "Aurora Civic Centre Project", balance: 350000, projectId: "project-aurora" },
    {
      id: "account-stage-foundation",
      name: "Foundation Package Stage",
      balance: 90000,
      projectId: "project-aurora",
      stageId: "stage-foundation",
    },
    {
      id: "account-stage-frame",
      name: "Structural Frame Stage",
      balance: 40000,
      projectId: "project-aurora",
      stageId: "stage-frame",
    },
    {
      id: "account-stage-envelope",
      name: "Envelope Works Stage",
      balance: 0,
      projectId: "project-aurora",
      stageId: "stage-envelope",
    },
  ],
  ledgerEntries: [
    {
      id: "entry-1",
      accountId: "account-project-aurora",
      amount: 600000,
      type: "deposit",
      reference: "Initial deposit",
      timestamp: "2026-04-01T09:00:00.000Z",
      sourceType: "funder",
      restrictedUse: false,
    },
    {
      id: "entry-2",
      accountId: "account-project-aurora",
      amount: -90000,
      type: "allocation_out",
      reference: "Allocate foundation stage",
      timestamp: "2026-04-02T11:00:00.000Z",
      stageId: "stage-foundation",
    },
    {
      id: "entry-3",
      accountId: "account-stage-foundation",
      amount: 90000,
      type: "allocation_in",
      reference: "Allocate foundation stage",
      timestamp: "2026-04-02T11:00:00.000Z",
      stageId: "stage-foundation",
      sourceType: "funder",
      restrictedUse: false,
    },
    {
      id: "entry-4",
      accountId: "account-project-aurora",
      amount: -40000,
      type: "allocation_out",
      reference: "Allocate frame stage",
      timestamp: "2026-04-03T14:20:00.000Z",
      stageId: "stage-frame",
    },
    {
      id: "entry-5",
      accountId: "account-stage-frame",
      amount: 40000,
      type: "allocation_in",
      reference: "Allocate frame stage",
      timestamp: "2026-04-03T14:20:00.000Z",
      stageId: "stage-frame",
      sourceType: "funder",
      restrictedUse: false,
    },
  ],
  auditLog: [],
};
