import type { SystemStateRecord } from "./shureFundModels";

export const initialSystemState: SystemStateRecord = {
  currentUserId: "user-commercial",
  users: [
    { id: "user-commercial", name: "Maya Singh", role: "commercial" },
    { id: "user-professional", name: "Owen Blake", role: "professional" },
    { id: "user-treasury", name: "Leah Mercer", role: "treasury" },
    { id: "user-executive", name: "Helen Grant", role: "executive" },
    { id: "user-funder", name: "Harbour Capital", role: "funder" },
    { id: "user-contractor", name: "Hawthorne Build", role: "contractor" },
    { id: "user-subcontractor", name: "Pinnacle Facades", role: "subcontractor" },
  ],
  projects: [
    { id: "project-aurora", name: "Aurora Civic Centre", location: "Leeds", status: "active", reserveBuffer: 50000 },
    { id: "project-meridian", name: "Meridian Life Sciences Hub", location: "Cambridge", status: "active", reserveBuffer: 30000 },
    { id: "project-harbour", name: "Harbour Exchange Retrofit", location: "Liverpool", status: "active", reserveBuffer: 40000 },
  ],
  stages: [
    {
      id: "stage-foundation",
      projectId: "project-aurora",
      projectName: "Aurora Civic Centre",
      projectLocation: "Leeds",
      name: "Foundation Package",
      description: "Substructure works covering excavation, reinforcement, pours, and foundation inspection close-out.",
      plannedStartDate: "2026-04-01",
      plannedEndDate: "2026-04-14",
      status: "approved",
      requiredAmount: 160000,
      releasedAmount: 0,
      evidenceRequirementIds: ["foundation-photos", "foundation-checklist"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      approvalSequence: ["commercial", "professional", "treasury"],
      contractorName: "Hawthorne Build",
      subcontractorName: "Groundline Civils",
      overrideActive: false,
      disputes: [],
      variations: [],
    },
    {
      id: "stage-frame",
      projectId: "project-aurora",
      projectName: "Aurora Civic Centre",
      projectLocation: "Leeds",
      name: "Structural Frame",
      description: "Primary steel frame fabrication, erection, and connection verification for the civic centre superstructure.",
      plannedStartDate: "2026-04-15",
      plannedEndDate: "2026-05-09",
      status: "blocked",
      requiredAmount: 240000,
      releasedAmount: 0,
      evidenceRequirementIds: ["frame-pack", "frame-checklist"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      contractorName: "Hawthorne Build",
      subcontractorName: "North Steel Systems",
      overrideActive: false,
      disputes: [
        {
          id: "dispute-frame-1",
          stageId: "stage-frame",
          title: "Certified value under review",
          reason: "Delivery note quantity does not match certified tonnage.",
          disputedAmount: 20000,
          status: "open",
          openedBy: "user-contractor",
          openedAt: "2026-04-04T09:30:00.000Z",
        },
      ],
      variations: [],
    },
    {
      id: "stage-envelope",
      projectId: "project-aurora",
      projectName: "Aurora Civic Centre",
      projectLocation: "Leeds",
      name: "Envelope Works",
      description: "Facade and weatherproofing works including mock-up approval, sealing details, and envelope completion checks.",
      plannedStartDate: "2026-05-10",
      plannedEndDate: "2026-06-04",
      status: "blocked",
      requiredAmount: 120000,
      releasedAmount: 0,
      evidenceRequirementIds: ["envelope-approval", "weatherproofing-checklist"],
      requiredApprovalRoles: ["commercial", "professional"],
      contractorName: "Hawthorne Build",
      subcontractorName: "Pinnacle Facades",
      overrideActive: false,
      onHold: true,
      disputes: [],
      variations: [
        {
          id: "variation-envelope-1",
          stageId: "stage-envelope",
          title: "Weatherproofing detail variation",
          reason: "Additional sealing detail required for revised facade interface.",
          amountDelta: 15000,
          status: "pending",
          createdBy: "user-contractor",
          createdAt: "2026-04-04T12:00:00.000Z",
        },
      ],
    },
    {
      id: "stage-meridian-shell",
      projectId: "project-meridian",
      projectName: "Meridian Life Sciences Hub",
      projectLocation: "Cambridge",
      name: "Shell And Core",
      description: "Shell and core delivery covering frame close-out, structure interfaces, and inspection pack approval.",
      plannedStartDate: "2026-04-03",
      plannedEndDate: "2026-04-28",
      status: "in_review",
      requiredAmount: 180000,
      releasedAmount: 0,
      evidenceRequirementIds: ["meridian-shell-pack", "meridian-shell-qc"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      approvalSequence: ["commercial", "professional", "treasury"],
      contractorName: "Axis Construction",
      subcontractorName: "Cityform Structures",
      overrideActive: false,
      disputes: [],
      variations: [],
    },
    {
      id: "stage-meridian-mep",
      projectId: "project-meridian",
      projectName: "Meridian Life Sciences Hub",
      projectLocation: "Cambridge",
      name: "MEP First Fix",
      description: "First-fix mechanical, electrical, and public health installations with associated test and quality records.",
      plannedStartDate: "2026-04-29",
      plannedEndDate: "2026-05-22",
      status: "blocked",
      requiredAmount: 90000,
      releasedAmount: 0,
      evidenceRequirementIds: ["meridian-mep-pack", "meridian-mep-check"],
      requiredApprovalRoles: ["commercial", "professional"],
      contractorName: "Axis Construction",
      subcontractorName: "Northpoint MEP",
      overrideActive: false,
      disputes: [],
      variations: [],
    },
    {
      id: "stage-harbour-demolition",
      projectId: "project-harbour",
      projectName: "Harbour Exchange Retrofit",
      projectLocation: "Liverpool",
      name: "Strip-Out And Demolition",
      description: "Demolition and strip-out works including waste segregation, temporary protection, and certified quantity review.",
      plannedStartDate: "2026-04-05",
      plannedEndDate: "2026-04-19",
      status: "disputed",
      requiredAmount: 110000,
      releasedAmount: 0,
      evidenceRequirementIds: ["harbour-demo-pack", "harbour-demo-check"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      approvalSequence: ["commercial", "professional", "treasury"],
      contractorName: "East Quay Projects",
      subcontractorName: "Urban Stripout",
      overrideActive: false,
      disputes: [
        {
          id: "dispute-harbour-demo-1",
          stageId: "stage-harbour-demolition",
          title: "Asbestos segregation scope disputed",
          reason: "Certified quantity includes disputed disposal uplift.",
          disputedAmount: 35000,
          status: "open",
          openedBy: "user-contractor",
          openedAt: "2026-04-05T08:40:00.000Z",
        },
      ],
      variations: [],
    },
    {
      id: "stage-harbour-facade",
      projectId: "project-harbour",
      projectName: "Harbour Exchange Retrofit",
      projectLocation: "Liverpool",
      name: "Facade Stabilisation",
      description: "Facade restraint and temporary works package covering stabilisation design coordination and site installation.",
      plannedStartDate: "2026-04-20",
      plannedEndDate: "2026-05-16",
      status: "blocked",
      requiredAmount: 150000,
      releasedAmount: 0,
      evidenceRequirementIds: ["harbour-facade-pack", "harbour-facade-check"],
      requiredApprovalRoles: ["commercial", "professional", "treasury"],
      contractorName: "East Quay Projects",
      subcontractorName: "Pinnacle Facades",
      overrideActive: false,
      disputes: [],
      variations: [
        {
          id: "variation-harbour-facade-1",
          stageId: "stage-harbour-facade",
          title: "Temporary works revision",
          reason: "Additional facade restraint detail required before progression.",
          amountDelta: 22000,
          status: "pending",
          createdBy: "user-contractor",
          createdAt: "2026-04-05T11:20:00.000Z",
        },
      ],
    },
  ],
  evidenceRequirements: [
    { id: "foundation-photos", stageId: "stage-foundation", label: "Foundation inspection photos", type: "file", required: true },
    { id: "foundation-checklist", stageId: "stage-foundation", label: "Concrete pour checklist", type: "form", required: true },
    { id: "frame-pack", stageId: "stage-frame", label: "Steel delivery pack", type: "file", required: true },
    { id: "frame-checklist", stageId: "stage-frame", label: "Frame erection checklist", type: "form", required: true },
    { id: "envelope-approval", stageId: "stage-envelope", label: "Facade mock-up approval", type: "file", required: true },
    { id: "weatherproofing-checklist", stageId: "stage-envelope", label: "Weatherproofing checklist", type: "form", required: true },
    { id: "meridian-shell-pack", stageId: "stage-meridian-shell", label: "Shell inspection pack", type: "file", required: true },
    { id: "meridian-shell-qc", stageId: "stage-meridian-shell", label: "Shell quality checklist", type: "form", required: true },
    { id: "meridian-mep-pack", stageId: "stage-meridian-mep", label: "MEP test pack", type: "file", required: true },
    { id: "meridian-mep-check", stageId: "stage-meridian-mep", label: "MEP quality checklist", type: "form", required: true },
    { id: "harbour-demo-pack", stageId: "stage-harbour-demolition", label: "Demolition completion pack", type: "file", required: true },
    { id: "harbour-demo-check", stageId: "stage-harbour-demolition", label: "Waste segregation checklist", type: "form", required: true },
    { id: "harbour-facade-pack", stageId: "stage-harbour-facade", label: "Facade stabilisation pack", type: "file", required: true },
    { id: "harbour-facade-check", stageId: "stage-harbour-facade", label: "Facade restraint checklist", type: "form", required: true },
  ],
  evidence: [
    { id: "evidence-foundation-photos", stageId: "stage-foundation", type: "file", status: "accepted", requirementId: "foundation-photos", name: "Foundation inspection photos", submittedAt: "2026-04-02T08:20:00.000Z" },
    { id: "evidence-foundation-checklist", stageId: "stage-foundation", type: "form", status: "accepted", requirementId: "foundation-checklist", name: "Concrete pour checklist", submittedAt: "2026-04-02T09:00:00.000Z" },
    { id: "evidence-frame-pack", stageId: "stage-frame", type: "file", status: "requires_more", requirementId: "frame-pack", name: "Steel delivery pack", submittedAt: "2026-04-03T10:15:00.000Z" },
    { id: "evidence-frame-checklist", stageId: "stage-frame", type: "form", status: "pending", requirementId: "frame-checklist", name: "Frame erection checklist", submittedAt: "2026-04-03T10:45:00.000Z" },
    { id: "evidence-envelope-approval", stageId: "stage-envelope", type: "file", status: "pending", requirementId: "envelope-approval", name: "Facade mock-up approval", submittedAt: "2026-04-03T13:00:00.000Z" },
    { id: "evidence-meridian-shell-pack", stageId: "stage-meridian-shell", type: "file", status: "accepted", requirementId: "meridian-shell-pack", name: "Shell inspection pack", submittedAt: "2026-04-03T08:10:00.000Z" },
    { id: "evidence-meridian-shell-qc", stageId: "stage-meridian-shell", type: "form", status: "accepted", requirementId: "meridian-shell-qc", name: "Shell quality checklist", submittedAt: "2026-04-03T08:35:00.000Z" },
    { id: "evidence-meridian-mep-pack", stageId: "stage-meridian-mep", type: "file", status: "accepted", requirementId: "meridian-mep-pack", name: "MEP test pack", submittedAt: "2026-04-04T14:00:00.000Z" },
    { id: "evidence-meridian-mep-check", stageId: "stage-meridian-mep", type: "form", status: "accepted", requirementId: "meridian-mep-check", name: "MEP quality checklist", submittedAt: "2026-04-04T14:20:00.000Z" },
    { id: "evidence-harbour-demo-pack", stageId: "stage-harbour-demolition", type: "file", status: "accepted", requirementId: "harbour-demo-pack", name: "Demolition completion pack", submittedAt: "2026-04-05T07:30:00.000Z" },
    { id: "evidence-harbour-demo-check", stageId: "stage-harbour-demolition", type: "form", status: "accepted", requirementId: "harbour-demo-check", name: "Waste segregation checklist", submittedAt: "2026-04-05T07:45:00.000Z" },
    { id: "evidence-harbour-facade-pack", stageId: "stage-harbour-facade", type: "file", status: "pending", requirementId: "harbour-facade-pack", name: "Facade stabilisation pack", submittedAt: "2026-04-05T12:15:00.000Z" },
  ],
  approvals: [
    { id: "approval-foundation-commercial", stageId: "stage-foundation", role: "commercial", status: "approved", approvedAt: "2026-04-02T10:00:00.000Z", approvedBy: "user-commercial" },
    { id: "approval-foundation-professional", stageId: "stage-foundation", role: "professional", status: "approved", approvedAt: "2026-04-02T10:30:00.000Z", approvedBy: "user-professional" },
    { id: "approval-foundation-treasury", stageId: "stage-foundation", role: "treasury", status: "approved", approvedAt: "2026-04-02T11:00:00.000Z", approvedBy: "user-treasury" },
    { id: "approval-frame-commercial", stageId: "stage-frame", role: "commercial", status: "pending" },
    { id: "approval-frame-professional", stageId: "stage-frame", role: "professional", status: "pending" },
    { id: "approval-frame-treasury", stageId: "stage-frame", role: "treasury", status: "pending" },
    { id: "approval-envelope-commercial", stageId: "stage-envelope", role: "commercial", status: "pending" },
    { id: "approval-envelope-professional", stageId: "stage-envelope", role: "professional", status: "pending" },
    { id: "approval-meridian-shell-commercial", stageId: "stage-meridian-shell", role: "commercial", status: "approved", approvedAt: "2026-04-03T09:20:00.000Z", approvedBy: "user-commercial" },
    { id: "approval-meridian-shell-professional", stageId: "stage-meridian-shell", role: "professional", status: "pending" },
    { id: "approval-meridian-shell-treasury", stageId: "stage-meridian-shell", role: "treasury", status: "pending" },
    { id: "approval-meridian-mep-commercial", stageId: "stage-meridian-mep", role: "commercial", status: "pending" },
    { id: "approval-meridian-mep-professional", stageId: "stage-meridian-mep", role: "professional", status: "pending" },
    { id: "approval-harbour-demo-commercial", stageId: "stage-harbour-demolition", role: "commercial", status: "approved", approvedAt: "2026-04-05T08:05:00.000Z", approvedBy: "user-commercial" },
    { id: "approval-harbour-demo-professional", stageId: "stage-harbour-demolition", role: "professional", status: "approved", approvedAt: "2026-04-05T08:10:00.000Z", approvedBy: "user-professional" },
    { id: "approval-harbour-demo-treasury", stageId: "stage-harbour-demolition", role: "treasury", status: "approved", approvedAt: "2026-04-05T08:15:00.000Z", approvedBy: "user-treasury" },
    { id: "approval-harbour-facade-commercial", stageId: "stage-harbour-facade", role: "commercial", status: "approved", approvedAt: "2026-04-05T10:30:00.000Z", approvedBy: "user-commercial" },
    { id: "approval-harbour-facade-professional", stageId: "stage-harbour-facade", role: "professional", status: "pending" },
    { id: "approval-harbour-facade-treasury", stageId: "stage-harbour-facade", role: "treasury", status: "pending" },
  ],
  ledgerAccounts: [
    { id: "account-project-aurora", name: "Aurora Civic Centre Project", balance: 240000, projectId: "project-aurora" },
    { id: "account-stage-foundation", name: "Foundation Package Stage", balance: 160000, projectId: "project-aurora", stageId: "stage-foundation" },
    { id: "account-stage-frame", name: "Structural Frame Stage", balance: 40000, projectId: "project-aurora", stageId: "stage-frame" },
    { id: "account-stage-envelope", name: "Envelope Works Stage", balance: 0, projectId: "project-aurora", stageId: "stage-envelope" },
    { id: "account-project-meridian", name: "Meridian Life Sciences Hub Project", balance: 110000, projectId: "project-meridian" },
    { id: "account-stage-meridian-shell", name: "Shell And Core Stage", balance: 120000, projectId: "project-meridian", stageId: "stage-meridian-shell" },
    { id: "account-stage-meridian-mep", name: "MEP First Fix Stage", balance: 20000, projectId: "project-meridian", stageId: "stage-meridian-mep" },
    { id: "account-project-harbour", name: "Harbour Exchange Retrofit Project", balance: 60000, projectId: "project-harbour" },
    { id: "account-stage-harbour-demolition", name: "Strip-Out And Demolition Stage", balance: 80000, projectId: "project-harbour", stageId: "stage-harbour-demolition" },
    { id: "account-stage-harbour-facade", name: "Facade Stabilisation Stage", balance: 50000, projectId: "project-harbour", stageId: "stage-harbour-facade" },
  ],
  ledgerEntries: [
    { id: "entry-1", accountId: "account-project-aurora", amount: 600000, type: "deposit", reference: "Initial deposit", timestamp: "2026-04-01T09:00:00.000Z", sourceType: "funder", restrictedUse: false },
    { id: "entry-2", accountId: "account-project-aurora", amount: -160000, type: "allocation_out", reference: "Allocate foundation stage", timestamp: "2026-04-02T11:00:00.000Z", stageId: "stage-foundation" },
    { id: "entry-3", accountId: "account-stage-foundation", amount: 160000, type: "allocation_in", reference: "Allocate foundation stage", timestamp: "2026-04-02T11:00:00.000Z", stageId: "stage-foundation", sourceType: "funder", restrictedUse: false },
    { id: "entry-4", accountId: "account-project-aurora", amount: -40000, type: "allocation_out", reference: "Allocate frame stage", timestamp: "2026-04-03T14:20:00.000Z", stageId: "stage-frame" },
    { id: "entry-5", accountId: "account-stage-frame", amount: 40000, type: "allocation_in", reference: "Allocate frame stage", timestamp: "2026-04-03T14:20:00.000Z", stageId: "stage-frame", sourceType: "funder", restrictedUse: false },
    { id: "entry-6", accountId: "account-project-meridian", amount: 250000, type: "deposit", reference: "Sponsor deposit", timestamp: "2026-04-02T08:00:00.000Z", sourceType: "funder", restrictedUse: false },
    { id: "entry-7", accountId: "account-project-meridian", amount: -120000, type: "allocation_out", reference: "Allocate shell and core", timestamp: "2026-04-03T09:45:00.000Z", stageId: "stage-meridian-shell" },
    { id: "entry-8", accountId: "account-stage-meridian-shell", amount: 120000, type: "allocation_in", reference: "Allocate shell and core", timestamp: "2026-04-03T09:45:00.000Z", stageId: "stage-meridian-shell", sourceType: "funder", restrictedUse: false },
    { id: "entry-9", accountId: "account-project-meridian", amount: -20000, type: "allocation_out", reference: "Allocate MEP first fix", timestamp: "2026-04-04T13:00:00.000Z", stageId: "stage-meridian-mep" },
    { id: "entry-10", accountId: "account-stage-meridian-mep", amount: 20000, type: "allocation_in", reference: "Allocate MEP first fix", timestamp: "2026-04-04T13:00:00.000Z", stageId: "stage-meridian-mep", sourceType: "funder", restrictedUse: false },
    { id: "entry-11", accountId: "account-project-harbour", amount: 190000, type: "deposit", reference: "Bridge facility drawdown", timestamp: "2026-04-04T07:30:00.000Z", sourceType: "funder", restrictedUse: false },
    { id: "entry-12", accountId: "account-project-harbour", amount: -80000, type: "allocation_out", reference: "Allocate demolition package", timestamp: "2026-04-05T08:00:00.000Z", stageId: "stage-harbour-demolition" },
    { id: "entry-13", accountId: "account-stage-harbour-demolition", amount: 80000, type: "allocation_in", reference: "Allocate demolition package", timestamp: "2026-04-05T08:00:00.000Z", stageId: "stage-harbour-demolition", sourceType: "funder", restrictedUse: false },
    { id: "entry-14", accountId: "account-project-harbour", amount: -50000, type: "allocation_out", reference: "Allocate facade stabilisation", timestamp: "2026-04-05T10:50:00.000Z", stageId: "stage-harbour-facade" },
    { id: "entry-15", accountId: "account-stage-harbour-facade", amount: 50000, type: "allocation_in", reference: "Allocate facade stabilisation", timestamp: "2026-04-05T10:50:00.000Z", stageId: "stage-harbour-facade", sourceType: "funder", restrictedUse: false },
  ],
  auditLog: [],
  eventHistory: [],
  lastActionOutcomes: {},
};
